version: '3.9'
services:
  challenge-java:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "challenge-java"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-challenge
      - rabbitmq
    container_name: challenge-java

  mongodb-challenge:
    image: mongo:latest
    container_name: "mongodb-challenge"
    ports:
      - "27017:27017"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./0-monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    container_name: prometheus

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./0-monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq

volumes:
  prometheus-data:
  grafana-data:
